let variant='drag',theme='dark',stage='install',generation=0,dragging=false,demoTimer, demoFinish;
const body=document.querySelector('main'),sheet=document.querySelector('.sheet');const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
const folder='<svg viewBox="0 0 72 72" aria-hidden="true"><path d="M9 24V18a4 4 0 0 1 4-4h16l7 7h23a4 4 0 0 1 4 4v30a4 4 0 0 1-4 4H13a4 4 0 0 1-4-4Z"/><path d="M9 26h54"/><path d="m28 47 8-15 8 15m-13-5h10" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg>';
function setTheme(value){theme=value;try{localStorage.setItem('relay-native-appearance',value)}catch{};document.documentElement.dataset.theme=theme;document.querySelector('iframe')?.contentWindow.postMessage({source:'preview-theme',theme},'*')}
function showInstall(){clearTimeout(demoTimer);clearTimeout(demoFinish);dragging=false;generation++;stage='install';sheet.classList.remove('folded');document.querySelector('iframe')?.remove();document.querySelector('.lockup').hidden=false;body.hidden=false;body.className='';body.innerHTML=`<div class="su-step">Install Relay</div><h1 class="su-title install-title">${variant==='drag'?'Drag Relay to<br>Applications.':'Install Relay.'}</h1><p class="su-copy">Click and hold the Relay icon. Move it onto<br>the Applications folder, then let go.</p><div class="scene"><svg class="thread" viewBox="0 0 344 196"><path d="M96 90 Q172 116 241 90"/></svg><button class="app-object" id="source" aria-label="Drag Relay to Applications"><img src="relayAppIcon.svg" alt="Relay"></button><div class="destination">${folder}</div><div class="app-object" id="ghost" aria-hidden="true"><img src="relayAppIcon.svg" alt=""></div><span class="object-label source-label">Relay</span><span class="object-label target-label">Applications</span></div><p id="hint">${variant==='drag'?'Pick up Relay. Drop it in the folder.':'One move. Then you’re ready.'}</p><div class="install-actions"><p class="notice" hidden></p><button class="su-primary" id="install">${variant==='drag'?'Install for me':'Install & open Relay'}</button></div>`;
 const travel=document.querySelector('.destination').getBoundingClientRect().x+44-document.querySelector('#source').getBoundingClientRect().x-38;document.querySelector('.scene').style.setProperty('--travel',travel+'px');document.querySelector('#install').onclick=install;wireDrag();if(variant==='drag')scheduleDemo(350)
}
function scheduleDemo(delay=5000){clearTimeout(demoTimer);if(reduced||variant!=='drag'||stage!=='install')return;const token=generation;demoTimer=setTimeout(()=>{if(token===generation)demonstrate()},delay)}
function demonstrate(){if(reduced||stage!=='install'||variant!=='drag')return;scheduleDemo();if(dragging)return;const scene=document.querySelector('.scene');clearTimeout(demoFinish);scene.classList.remove('demonstrating');void scene.offsetWidth;scene.classList.add('demonstrating');demoFinish=setTimeout(()=>scene.classList.remove('demonstrating'),3450)}
function wireDrag(){const icon=document.querySelector('#source'),scene=document.querySelector('.scene'),target=document.querySelector('.destination'),hint=document.querySelector('#hint');let origin,good=false;
 icon.onpointerdown=e=>{if(stage!=='install')return;dragging=true;good=false;clearTimeout(demoTimer);clearTimeout(demoFinish);scene.classList.remove('demonstrating');origin={x:e.clientX,y:e.clientY};icon.setPointerCapture(e.pointerId);icon.style.transition='none'};
 icon.onpointermove=e=>{if(!dragging)return;const dx=e.clientX-origin.x,dy=e.clientY-origin.y;icon.style.transform=`translate(${dx}px,${dy}px) rotate(-3deg) scale(1.06)`;const b=target.getBoundingClientRect();good=e.clientX>b.left-10&&e.clientX<b.right+10&&e.clientY>b.top-10&&e.clientY<b.bottom+10;scene.classList.toggle('targeted',good);hint.textContent=good?'Let go. Relay goes here.':'Keep holding. Move to Applications.';document.querySelector('.thread path').setAttribute('d',`M${96+dx} ${90+dy} Q172 ${116+dy*.25} 241 90`)};
 const end=()=>{if(!dragging)return;dragging=false;icon.style.transition='transform .42s var(--soft)';icon.style.transform='';document.querySelector('.thread path').setAttribute('d','M96 90 Q172 116 241 90');scene.classList.remove('targeted');if(good)install();else {hint.textContent='Try again, or choose Install for me.';scheduleDemo(700)}};icon.onpointerup=end;icon.onpointercancel=()=>{good=false;end()};icon.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();install()}};
}
async function install(){if(stage!=='install')return;stage='moving';clearTimeout(demoTimer);clearTimeout(demoFinish);const token=generation,button=document.querySelector('#install'),icon=document.querySelector('#source'),scene=document.querySelector('.scene');scene.classList.remove('demonstrating');scene.classList.add('targeted');document.querySelector('.notice').hidden=true;button.disabled=true;button.textContent='Moving Relay…';document.querySelector('#hint').textContent='Installing in Applications…';icon.style.transition=reduced?'none':'transform .65s var(--soft)';icon.style.transform='translate('+scene.style.getPropertyValue('--travel')+',0) scale(.72)';const result=await window.migration.relocate().catch(error=>({ok:false,error:error.message}));if(token!==generation)return;if(!result.ok){stage='install';button.disabled=false;button.textContent='Try again';icon.style.transform='';scene.classList.remove('targeted');const note=document.querySelector('.notice');note.hidden=false;note.textContent=result.error;scheduleDemo();return}await new Promise(r=>setTimeout(r,reduced?0:720));if(token!==generation)return;button.textContent='Opening Relay…';document.querySelector('#hint').textContent='Opening the installed Relay app…'}

document.querySelector('#themeToggle').onclick=()=>setTheme(theme==='dark'?'light':'dark');
document.querySelector('#closeX').onclick=()=>window.close();
try{theme=localStorage.getItem('relay-native-appearance')||theme}catch{}
setTheme(theme);showInstall();
